### ISSUE TITLE
No compatible with cdk 10.1 / material 10.1

### ISSUE THREAD

**Issue by tsiegleauq** [shlomiassaf/ngrid#111]
#### What is the expected behavior?

Ngrid should be compatible with CDK 10.1 and material 10.1

#### What is the current behavior?

Upon loading any ngrid directive, the error:
"Cannot read property 'nativeElement' of null"
was thrown.

#### What are the steps to reproduce?

Use ngrid as usual, update CDK and Material to 10.1
https://stackblitz.com/edit/pebula-ngrid-starter-vgeelc?file=package.json

#### Which versions of Angular, CDK, Material, NGrid, OS, TypeScript, browsers are affected?

Angulae 10
CDK 10.1
Ngrid 2.0.0
Typescript 3.9
Chromium latest

#### Is there anything else we should know?

Downgrading fixes the issue so ngrid works again.
package.json
```json
 "@angular/cdk": "~10.0.0",
 "@angular/cdk-experimental": "~10.0.0",
 "@angular/material": "~10.0.0",
```

**Comment by shlomiassaf** [comment]
@tsiegleauq Thanks for the update, I will look into it.
They keep changing the APIs of the drag and drop and these components are not super friendly to customise... hell.

**Comment by shlomiassaf** [comment]
I see that in 10.2.2 they re-exported the missing tokens, which seems to be working.
However, they changed the differ for rows in the main table, so it will not work until I upload the new version.
Once uploaded it will support 10.2.2

**Comment by shlomiassaf** [comment]
See `@pebula/ngrid@2.1.0` & `@pebula/ngrid-material@2.1.0` for the fix.

**note that it requires CDK 10.2.2**

**Comment by shlomiassaf** [comment]
I assume this one is fixed, please re-open if problem persist.
