### ISSUE TITLE
Using ngrid in a scenario where you have dynamic columns

### ISSUE THREAD

**Issue by sheemjayaraj** [shlomiassaf/ngrid#116]
#### Please describe the feature you would like to request.
When you have column headers or labels and the data for columns added dynamically, say a table that shows the properties of list of vehicles, where each time we pick a vehicle from a list, the columns changes for each vehicle
option 1 - 2 wheeler - columns= [vehicleCode, noOfWheels, wheel1Pressure, wheel2Pressure
[vehicleReport.docx](https://github.com/shlomiassaf/ngrid/files/5286315/vehicleReport.docx)
]
option2- 4 wheeler - columns= [vehicleCode, noOfWheels, wheel1Pressure, wheel2Pressure ,wheel3Pressure, 
                                                      wheel4Pressure]

**Comment by shlomiassaf** [comment]
What did you try to do to solve the issue?
Where are you stuck?

I can't help here.

With all good will, I'm not able to do technical support... Most of the things are in the docs

Try reading this section:

https://shlomiassaf.github.io/ngrid/features/column/switching-column-definitions
