### ISSUE TITLE
Issues with Target Events plugin

### ISSUE THREAD

**Issue by DrDonkeyPunch** [shlomiassaf/ngrid#117]
Hello,

First of all, thanks for the great work on the lib. 

I've been trying to use the Target Events on a grid in my project to provide an Excel like experience when navigating with the keyboard. I encountered some unexpected behaviors : 

1. When you rapidly press the down arrow key twice, the next cell appears selected rather than focused
2. If you repeat the previous case multiple times, the focus sometimes  jumps several rows (5-6 rows jumps in my case)
3. When you play with long press and short press on the down / up arrow key, you end up losing the focused cell. You can still go up and down the grid but the focused cell is not visible.
4. Once you've reached the bottom of the grid, any additionnal down arrow key pressing will scroll the main page. If you then press the up arrow key, you can scroll the grid but the main page won't scroll back to where it was.

I succesfully reproduced all these cases on the demo website.

Thanks

**Comment by shlomiassaf** [comment]
Hi @DrDonkeyPunch 

Thanks for the update

I guess 1 & 2 both manifest in 3 and are all probably the same issue.
I will look into it once I have time, if you want to jump in fell free, all help is appreciated.

As for 4, I guess that's the default behaviour of the underlaying components, I will check it as well.
