### ISSUE TITLE
columnDef override error

### ISSUE THREAD

**Issue by andrewalderson** [shlomiassaf/ngrid#118]
I am getting the following error after adding ngrid to a new angular 10 cli project
```
ERROR in node_modules/@pebula/ngrid/lib/grid/columns/group-column.d.ts:52:5 - error TS2610: 'columnDef' is defined as an accessor in class 'PblMetaColumn', but is overridden here in 'PblColumnGroup' as an instance property.
```

I have been trying to figure out why I am getting the error because all of the demo projects in the repo are working with the same version of ngrid. Regardless, the override should be fixed and be consistent.

As a quick fix simply patching the group-colum.d.ts file that is installed and making the property a getter fixes the error.

**Comment by shlomiassaf** [comment]
I need more info...

The version you use for

  - NGrid
  - Angular core
  - Angular CLI
  - TypeScript

**Comment by andrewalderson** [comment]
NGrid - 2.1.0
Angular Core - 10.1.4
Angular CLI - 10.1.4
Typescript - 4.0.2

This is a new angular cli project and I created it with the strict flag set to true. I don't know why it is checking the node_modules folder for errors. I tried turning off the strict checking but I still get the error.

**Comment by shlomiassaf** [comment]
The repo's TS version is `~3.9.6` so it's probably due to that, 4.0 probably catch this one.

Valid issue, i'll fix.
