### ISSUE TITLE
group width calculation in RTL mode is invalid

### ISSUE THREAD

**Issue by shlomiassaf** [shlomiassaf/ngrid#130]
#### What is the expected behavior?

When calculating group width in RTL mode the group width's are overflowing the column's and in total overflow their own row container.

#### What is the current behavior?
Group width's should be the same in RTL and LTR modes.

#### What are the steps to reproduce?
Go to https://shlomiassaf.github.io/ngrid/demos/infinite-scroll-performance
Toggle RTL to be ON
On the column menu (action row) click "Restore Columns", this will trigger re-calc of all column widths.

Group width's are invalid.

**Comment by shlomiassaf** [comment]
@ronnetzer would you like to take this one? if not i'll do it no problem.

**Comment by ronnetzer** [comment]
Same problem as #129

Change the app to be RTL first and you'll see it works as expected, toggle back to LTR and you'll see it still 'stuck' in RTL
