### ISSUE TITLE
Wrong calculation of widths when changing the zoom in the browser. 

### ISSUE THREAD

**Issue by dmitry-bas** [shlomiassaf/ngrid#138]
Wrong calculation of widths when changing the zoom in the browser. 

The scroll bar appears and disappears on mouse move.

**Comment by shlomiassaf** [comment]
What is the OS & browser? Which ngrid version?

Here's V3 (alpha) on my machine (OSX - Chrome)

![image](https://user-images.githubusercontent.com/5377501/99591905-20920200-29f8-11eb-85d8-151d5ceff85f.png)

**Comment by shlomiassaf** [comment]
Since I get no response i'll close this one.
Please re-open with new information, if you can.

Thanks.
