### ISSUE TITLE
Transformation function is not receiving a valid value to transform

### ISSUE THREAD

**Issue by jean-merelis** [shlomiassaf/ngrid#158]
#### What is the expected behavior?
The function should receive the value in the first argument

#### What is the current behavior?
The function is receiving undefined value in the first argument

#### What are the steps to reproduce?
https://stackblitz.com/edit/pebula-ngrid-starter-m9i6cp?file=app/app.component.ts

#### Which versions of Angular, CDK, Material, NGrid, OS, TypeScript, browsers are affected?
Angular 11
NGrid 3.0.0

**Comment by jean-merelis** [comment]
For some reason it seems that the getValue method was not binded and "this" is undefined too
![image](https://user-images.githubusercontent.com/1755960/103657834-2791b700-4f49-11eb-8aba-1a29bd2be6a3.png)

**Comment by shlomiassaf** [comment]
Released in 3.0.1, thank you
