### ISSUE TITLE
Sticky Column in 3.0.0 not working

### ISSUE THREAD

**Issue by digoburigo** [shlomiassaf/ngrid#160]
#### What is the expected behavior?
![image](https://user-images.githubusercontent.com/28462822/103705563-056c5900-4f8a-11eb-9d10-7a2ad69506ed.png)
When i set the ```pin``` to ```'start'``` in the column definition in the version 2.3.1 works as expected like in the image above

#### What is the current behavior?
When upgrading to version 3.0.0 this feature don't work anymore 

#### What are the steps to reproduce?
You cant set the ```pin: 'start``` in the ```id``` column definition in the starter below and change the versions to ```2.3.1``` and ```3.0.0``` to see that is not working.
StackBlitz starter: [stackblitz.com/edit/pebula-ngrid-starter](https://stackblitz.com/edit/pebula-ngrid-starter?file=app%2Fapp.component.ts)<br/>

``` 
    ...
    "@angular/core": "~11.0.5",
    "@angular/cdk": "11.0.3",
    "@angular/material": "11.0.3",
    ...
    "@pebula/ngrid": "3.0.0",
    "@pebula/ngrid-material": "3.0.0",
    ...
    "typescript": "~4.0.5",
```

   Tested on
```
   OS: Linux Mint
   Browser: Chrome 87.0.4280.88
```

Or it changed in version 3.0.0 and I didn't see in the docs. 
Thanks for this library

**Comment by shlomiassaf** [comment]
Yes
I will dig into it

**Comment by skrtheboss** [comment]
@shlomiassaf is there any progress on this? I would need it really badly.

**Comment by karthickrajanc** [comment]
@shlomiassaf Any updates on this issue?

**Comment by shlomiassaf** [comment]
This will become a priority now, we also need this where I work so I will try to push this one forward

**Comment by shlomiassaf** [comment]
Now in 3.1.2
