### ISSUE TITLE
Enhance sorting and filtering APIs

### ISSUE THREAD

**Issue by shlomiassaf** [shlomiassaf/ngrid#19]
- [x] - Make the API's more clear
- [x] - Support filter predicates through column definitions (like sorting)
- [x] - Align sort and filter APIs to match as much as possible
- [x] - Expose filtered and sorted data through `PblDataSource`
- [x] - Document filtering

**Comment by ek2dev** [comment]
would be great to have access to filtered data. at least to count, i.e. to be able to show how many items stayed after filtering

also selection column should select only items which visible after filtering.

**Comment by shlomiassaf** [comment]
@ek2dev @tsiegleauq See the docs in the [Features -> Column -> Column Filters page](https://shlomiassaf.github.io/ngrid/ngrid#/features/column-filtering)

version `1.0.0-alpha.23`
