### ISSUE TITLE
Error in grid when using Angular Material 11

### ISSUE THREAD

**Issue by jmcontreras1213** [shlomiassaf/ngrid#204]
Hi, 

I tried you component and getting this error:

error NG8002: Can't bind to 'columns' since it isn't a known property of 'pbl-ngrid'.
1. If 'pbl-ngrid' is an Angular component and it has 'columns' input, then verify that it is part of this module.
2. If 'pbl-ngrid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
4.

**Comment by fbaldo31** [comment]
It looks like a missing dependency you should check if you have correctly imported the module in your app.module or shared one if it is your case.

Seems that `ng add` won't do it for this module
