### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by rubiesonthesky** [shlomiassaf/ngrid#249]
Is there any update on the plan, when this library would support Angular 13?

There are two PRs that would make using Angular 13 possible:

- https://github.com/shlomiassaf/ngrid/pull/220
- https://github.com/shlomiassaf/ngrid/pull/238

Some problems are at least coming from Typescript update and not necessary Angular update but since Angular updates the Typescript version, they are related.

**Comment by shlomiassaf** [comment]
Hi

See [release 4.0.1](https://github.com/shlomiassaf/ngrid/releases/tag/4.01) for fix of #220 

For #238 we will release v5 

Thanks.

**Comment by shlomiassaf** [comment]
Please see v5, with angular 14 support.
