### ISSUE TITLE
Change Selection Checkbox Color

### ISSUE THREAD

**Issue by andybond006** [shlomiassaf/ngrid#43]
#### Please describe the feature you would like to request.

I would like to have the option of specifying "accent" as the color that the checkboxes use when you set `matCheckboxSelection="selection"` on the `pbl-ngrid` component.

#### What is the use-case or motivation for this proposal?

It would just be a nice option to have.

**Comment by shlomiassaf** [comment]
Done in `1.0.0-rc.6`, [read more here](https://shlomiassaf.github.io/ngrid/plugins/ngrid-material/selection-column#checkbox-color)node -v

**Comment by andybond006** [comment]
Awesome! Thanks! Really love the grid by the way!

**Comment by shlomiassaf** [comment]
@andybond006 If you don't see the updated docs in the app, please refresh it was just uploaded.
