### ISSUE TITLE
Custom Sort Function for grid columns and Custom Filtering for excelMenu

### ISSUE THREAD

**Issue by phantasma2983** [shlomiassaf/ngrid#45]
#### Please describe the feature you would like to request.
Ability to pass sortFunction in column definition or define sortFunction based on column 'type'
Ability to pass custom filterFunction to excelMenu for the Search functionality.

#### What is the use-case or motivation for this proposal?
In my case each cell contains an object with an 'html' key for display and a 'raw' value key. I display the html inside the cell template but would like to be able to sort by the raw value.

#### Is there anything else we should know?
Thanks

**Comment by shlomiassaf** [comment]
The `sort` property in the column definitions accepts a boolean or a sorting function, you can read more [here](https://shlomiassaf.github.io/ngrid/features/column/column-sort)

The `filter` property in the column definitions accepts a filtering function, you can read more [here](https://shlomiassaf.github.io/ngrid/features/column/column-filter)

Both document pages comes with detailed examples....

---

Note the a bug in column specific sorting was found and fixed, use version `1.0.0-rc.7` for it.

Filtering works properly

--
