### ISSUE TITLE
Error compiling with angular cli 8.2.5

### ISSUE THREAD

**Issue by rpijnacker** [shlomiassaf/ngrid#49]
#### What is the expected behavior?

Compile and run as previous version

#### What is the current behavior?

Compilation breaks

#### What are the steps to reproduce?

Use ngrid as source inside a project. Then upgrade from angular 8.0.3 to latest angular cli version

and this error occurs when compiling

ERROR in libs/ngrid/src/lib/data-source/data-source-adapter.helpers.ts(76,13): error TS2322: Type 'DEEP_COMPARATORS<"data" | "filter" | "sort" | "pagination">[P]' is not assignable to type '(prev: PblDataSourceTriggerCache[P], curr: PblDataSourceTriggerCache[P]) => boolean'.
Type '((prev: RefreshDataWrapper, curr: RefreshDataWrapper) => boolean) | ((prev: DataSourceFilterType, curr: DataSourceFilterType) => boolean) | ((prev: PblNgridDataSourceSortChange, curr: PblNgridDataSourceSortChange) => boolean) | ((prev: { ...; }, curr: { ...; }) => boolean)' is not assignable to type '(prev: PblDataSourceTriggerCache[P], curr: PblDataSourceTriggerCache[P]) => boolean'.

**Comment by shlomiassaf** [comment]
Doesn't look I can do much to help with this case as this scenario is not supported...

I strongly advise using the original packages from npm, or at least your own build from a private package registry,.
