### ISSUE TITLE
ngridCellClass and ngridCellStyle not applying the style due to empty differ.value

### ISSUE THREAD

**Issue by t00** [shlomiassaf/ngrid#51]
When defining a column with pblNgridCellDef I tried to apply a class (and style) to the parent element. Directives seem to execute fine, updateParent method is called but the class is not added to the pbl-ngrid-cell.

To walk through the code, in updateParent a following check returns true:

if (this._classDiffer && this._classDiffer.hasValueChanged())

_lastClass is empty

the list this._classDiffer.value is empty so Object.keys(this._classDiffer.value) won't iterate.

Class differ's _lastSetValue contains the expected class object but this._parent.classList does not contain the expected class.

the loop for (const key of Object.keys(this._classDiffer.value)) is never executed.

What might be the reason for classDiffer to contain the expected value without ever calling updateParent?

At the same time rowClassUpdate with ngDoCheck is used to change the class for a row (returning a single string class or null if no class need to be applied) - rowClassUpdate returning a dictionary { [class: string]: boolean } does not seem to work!

Or is there something else which needs to be set to make ngridCellClass work?

Using 1.0.0-rc.9 with angular 8.2.7.

**Comment by shlomiassaf** [comment]
Hi,
Thanks for updating.

For me to help you I need some kind of reproduction, [stackblitz.com/edit/pebula-ngrid-starter](https://stackblitz.com/edit/pebula-ngrid-starter?file=app%2Fapp.component.ts) is the best way to do it, everything is set up, just write your code and see the bug reproduces and I will try to help from there.

**Comment by t00** [comment]
Sorry I have trouble reproducing the issue as it must be a mixture of using row and cell styling causing the updating not to work. For now I have a workaround (ngClass) so I will close the issue but if I will stumble upon the problem again, I will investigate the problem more.
