### ISSUE TITLE
Support Angular 9 with and without IVY

### ISSUE THREAD

**Issue by magnusbakken** [shlomiassaf/ngrid#62]
You may already know this, but in case you haven't tested upgrading I thought I would point out that NGrid currently doesn't work with Ivy on Angular 9. Angular 9 by itself with Ivy disabled actually seems to work fine.

The Ivy compilation goes okay, but at runtime you get this error:

    main.ts:13 TypeError: Cannot read property 'get' of undefined
        at NgModuleRef$1.get (core.js:35997)
        at NgModuleRef$1.get componentFactoryResolver [as componentFactoryResolver] (core.js:36003)
        at Function.loadCommonTemplates (pebula-ngrid.js:14758)
        at new PblNgridModule (pebula-ngrid.js:14711)
        at Object.PblNgridModule_Factory [as factory] (pebula-ngrid.js:14775)
        at R3Injector.hydrate (core.js:18516)
        at R3Injector.get (core.js:18278)
        at core.js:18208
        at Set.forEach (<anonymous>)
        at new R3Injector (core.js:18204)

I don't know enough about Ivy to tell what the error is, but I would guess it has to do with the module declaration.

I've added an Angular 9 project based on the starter template here: https://github.com/magnusbakken/ngrid-ivy I basically just ran `ng update @angular/cli@next @angular/core@next`, and had to work around one type error to do with `require.resolve()`.

**Comment by shlomiassaf** [comment]
@magnusbakken Thanks for updating.

I assumed it will not work on angular 9 under IVY because it was not compiled with the proper IVY supporting environment (mainly ng-packagr and CLI for IVY)

Once 9 is official, I will start working on the solution.

There are several deprecations that needs to be addressed, not only on the library side but also on the build process, demo application etc...

Thanks again.

**Comment by jvictorsoto** [comment]
Angular 9 was released Feb, 6. Any plans on supporting it soon?

**Comment by shlomiassaf** [comment]
Hi

I’m planning to start the work soon, meter of a few weeks,  aligning with v9 and material 9

**Comment by shlomiassaf** [comment]
I've summed up the worked required for upgrading in #79 

I will close this issue now as V9 upgrade will be managed from #79 

Thank you all for your support!
