### ISSUE TITLE
Internet Explorer width calculations is stuck in a loop

### ISSUE THREAD

**Issue by t00** [shlomiassaf/ngrid#74]
The issue is difficult to reproduce as it only shows when certain amount of parent objects is present, with complex DOM, some flex containers. Surely due to slow IE rendering, width calculation stays behind of actual rendering causing infinite recalculation of a container width.

The example firefox grid placement settles at 919.75px and stays the same until parent container is resized:

<div pbl-ngrid-fixed-meta-row-container="header" style="flex: 0 0 auto; overflow: hidden; width: 919.75px;" ng-reflect-type="header">
<div class="pbl-cdk-table" style="width: 919.75px;">

On IE, for the same resolution the width is changing between 3 different values with sub-second interval:

<div style="flex:0 0 auto; width: 873px; overflow: hidden;" pbl-ngrid-fixed-meta-row-container="header" ng-reflect-type="header">
<div class="pbl-cdk-table" style="width: 873px;">

<div style="flex:0 0 auto; width: 907px; overflow: hidden;" pbl-ngrid-fixed-meta-row-container="header" ng-reflect-type="header">

<div style="flex:0 0 auto; width: 890px; overflow: hidden;" pbl-ngrid-fixed-meta-row-container="header" ng-reflect-type="header">

The result looks like this:

![ie width](https://user-images.githubusercontent.com/1933165/72155096-3b442500-33aa-11ea-85c4-a74dc781dea4.gif)

I checked it on the rc11 build before refactorings and rc13 as well - no difference. Is there a way to implement a delay for updating widths? I don't consider IE top priority really but not supporting it due to such issue would not be ideal - if resizing delay can be introduced, IE users will notice a problem only when window or parent container is resized which would be a more bearable than above :)

**Comment by shlomiassaf** [comment]
Sure, got it.

I'll try to find some fix... thing is i'm using OSX so it will be challenging working on a VM :)

**Comment by shlomiassaf** [comment]
@t00 Can you help here and provide a StackBlitz with a working example?

**Comment by shlomiassaf** [comment]
@t00 another thing that might help here..

Do you think #73 might solve this? seems related...

Resize events are debounced between animation frames so it's a delay

**Comment by shlomiassaf** [comment]
Closing this as long time have passed and we're in version 3 now.

Re-open if still occures.

**Comment by t00** [comment]
Thanks for looking into the issue anyway, I gave up entirely from supporting Internet Explorer - it is madness :)
