### ISSUE TITLE
Rendering issue horizontal scroll

### ISSUE THREAD

**Issue by digoburigo** [shlomiassaf/ngrid#89]
#### What is the expected behavior?
In older version of this library i was not having any troubles in rendenring the table with horizontal scroll

![image](https://user-images.githubusercontent.com/28462822/78956825-ebb0ea80-7ab9-11ea-90f2-6e515bda2ad5.png)

```
"@pebula/ngrid": "1.0.0-rc.13",
"@pebula/ngrid-material": "1.0.0-rc.13",
```

#### What is the current behavior?

But now when updated to the recent version, the rendering process doesn't work anymore

![image](https://user-images.githubusercontent.com/28462822/78956953-519d7200-7aba-11ea-9397-ca2adbd2a87c.png)

```
"@pebula/ngrid": "^2.0.0-rc.1",
"@pebula/ngrid-material": "^2.0.0-rc.1",
```

#### Is there anything else we should know?
I just updated to most recent versions of Angular and this library
```"@angular/core": "~9.1.1",```

**Comment by shlomiassaf** [comment]
Hi,

Thanks for posting.

I could not reproduce it in the demo application.

Is it possible that you create a stackblitz demo with this being reproduced?

It might only happen in specific scenarios, for example, when virtual scroll is disabled or when using with another plugin...

Please provide something that I can start working with.

Thank you!

**Comment by digoburigo** [comment]
I done the example in stackblitz https://stackblitz.com/edit/angular-qrmitw, but was not doing the error, so with that, i gone back to my project and see where the bug was ocurring, i was using a this css 
```
 div[pbl-ngrid-fixed-meta-row-container] > div:first-child {
    display: none;
  }
```
Because was creating a extra space in the top of the table, then i changed to
```
 div[pbl-ngrid-fixed-meta-row-container] > div:first-child {
    height: 1px;
  }
```
And worked, i think this was messing with the calculations of the render process, but now it's working fine

**Comment by shlomiassaf** [comment]
@digoburigo Thanks!
