### ISSUE TITLE
scrollTo

### ISSUE THREAD

**Issue by tamtakoe** [shlomiassaf/ngrid#9]
Hello! Thank you for perfect library. What about scrollTo method for virtual scroll?

**Comment by tsiegleauq** [comment]
`CdkVirtualScrollViewport.scrollToIndex(indexNumber);`
works in this library. I am using it myself.

```ts
@ViewChild(PblNgridComponent)
    private ngrid: PblNgridComponent;

public scrollToPosition(index: number): void {
    this.ngrid.viewport.scrollToIndex(index);
}
```

**Comment by shlomiassaf** [comment]
Yep, @tsiegleauq is right, `this.ngrid.viewport` is the instance of `PblCdkVirtualScrollViewportComponent` that extends `CdkVirtualScrollViewport` so all functionallity is there.

I should note that `scrollToIndex` support is based on the virtual strategy implementation. So, for fixed scroll strategy the CDK has an implementation but for `AutoSizeVirtualScrollStrategy`  there is [no support](https://github.com/angular/components/blob/master/src/cdk-experimental/scrolling/auto-size-virtual-scroll.ts#L75) at the moment.
works with fixed virtual scroll strategy, au

**Comment by tamtakoe** [comment]
Hmm... I see code just with custom strategies (standard strategy doesn't work). Do you have any example with table + virtual scroll + lazy loading + sticky header + working scrollTo?

**Comment by shlomiassaf** [comment]
@tamtakoe I don't have such a specific example.

[here is](https://stackblitz.com/edit/pebula-ngrid-starter-1wok1b?file=app%2Fapp.component.html) an example for virtual scroll with scrollTo the middle and to a specific item, the specific item one will work **only with fixed strategy which is what's set in this example.

**Comment by tamtakoe** [comment]
@shlomiassaf It is not so difficult. Difficult is if your elements change their hight dynamically (collapse/expand) :-) I implemented this behavior (with lots of hacks) with ag-grid... But I don't want to use this library anymore.

Will wait this implementation in CDK. Thanks for the example!
